# Generated by Django 5.2.3 on 2025-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_uploadedimage_analysis_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPAScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("script_file", models.FileField(upload_to="rpa_scripts/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
