# Generated by Django 5.2.3 on 2025-06-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0003_rpascript"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("highschool", models.CharField(max_length=255)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "course_interested",
                    models.CharField(
                        choices=[
                            ("Computer Science", "Computer Science"),
                            ("Data Science", "Data Science"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            ("Mechanical Science", "Mechanical Science"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Form Entries",
            },
        ),
    ]
