# Generated by Django 5.2.3 on 2025-06-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0004_formentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormEntry",
        ),
        migrations.AddField(
            model_name="rpascript",
            name="data_file",
            field=models.FileField(blank=True, null=True, upload_to="rpa_scripts/"),
        ),
    ]
